### ISSUE TITLE
Remove active solution layer from type entity not possible!

### ISSUE THREAD

**Issue by wd21sos** [mkmk89/UnmanagedLayerBulkRemover#4]
I tried to delete an active solution layer which is on type entity. But unfortunately this is not supported! Why is it possible to pick the component type "entity" if it is not supported? This should definitely be supported as the active solution layer is mostly connected to the type entity.

## ERROR MESSAGE

Removing layer Entity with Id b80fedb4-0b6b-ed11-a362-0050569c4dd8.. 
Removing layer Entity with Id b80fedb4-0b6b-ed11-a362-0050569c4dd8 failed with error: RemoveActiveCustomizations is not supported for components of type Entity.

**Comment by mkmk89** [comment]
The reason why it is possible to select unsupported component is that Microsoft keeps adding more and more components as supported, so this way we don't need to follow MS every time they extend it, instead we expose all and handle error when unsupported one is selected. You may want to remove active layers from all child components like forms, views, fields rather than entity itslef.
